### ISSUE TITLE
There is nothing after execution.

### ISSUE THREAD

**Issue by gaolv123tyu** [let-z-go/aspector#1]
HI，
My cmd is   "${GOPATH:-$(go env GOPATH)}/bin/aspector" future_predictor.go,
but there is nothing after execution. except :
=========================
/*
 * Generated by Aspector. DO NOT EDIT!
 */

package predict

==========================

future_predictor.go content like this:

type predictor struct {

}

// 专注于预估服务，切片等由代理服务完成
//
func (self *predictor) Predict(req *Request) (res interface{}, err error) {

	return nil, nil
}

**Comment by roy2220** [comment]
Aspector only works for interfaces:
1. Create a new file `future_predictor_interface.go`:

```
package predict

type IPredictor interface {
    Predict(req *Request) (res interface{}, err error)
}
```

2. Execute `"${GOPATH:-$(go env GOPATH)}/bin/aspector" future_predictor_interface.go`
3. Then you can write somethings like:
```
o := &predictor{...} // You predictor
pw := &IPredictorWrap{ // Wrap generated
    Origin: o, 
} 
pw.AddMethodInterceptor(...) // Add your interceptor
var p IPredictor = pw
p.Predict(...)
```
4. 老铁，还不懂的话可以加企鹅1332666290
